#!/bin/sh -c 'echo This file is meant to be sourced.'

alias LaunchCFMApp='/System/Library/Frameworks/Carbon.framework/Versions/Current/Support/LaunchCFMApp' 
    # Code Fragment Management applications can't be run ./app :-)
alias apps="ps x -o command | grep '[ ]-psn_' | sort" 
    # List all running Aqua applications
alias idle="ioreg -c IOHIDSystem | awk '/HIDIdleTime/ {print \$NF/1000000000; exit}'" 
    # This returns the number of seconds since I typed anything or moved the mouse
function DS_clean () { dot_clean -n "$1"; find "$1" -name \.DS_Store -delete; }
function d2x () { plutil -convert xml1 "$@"; }

## Aqua/GUI related helpers
function app () { ps xc -o command | egrep -c "^$*$" ; }
function Aqua () { osascript -e 'tell application "System Events" to do shell script "'"$*"'"'; }

function ql () { qlmanage -p "$@" >/dev/null ; }

function qapp () 
{   # Use AppleScript to quit a running Aqua application, the application name does not need to be quoted
 
    osascript -e 'tell application "Dock"' -e 'tell application "'"$*"'" to quit' -e 'end tell'
}

function lapp () 
{   # Use AppleScript to launch an Aqua application, the application name need not be quoted
 
    osascript -e 'tell application "Dock"' -e 'launch application "'"$*"'"' -e 'end tell' 
}

function fapp ()
{   # Use perl to find an Aqua application by bundle ID
    perl -MMac::Processes -e 'printf "%s\n", LSFindApplicationForInfo(undef, "'"$1"'")'
}

function carbErr ()
{   # Lookup carbon error codes
    if [ "$1" == "" -o "$2" != "" ];then 
        echo "Usage: $FUNCNAME errno"
    else 
        grep "$1" /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/CarbonCore.framework/Headers/MacErrors.h
    fi
}

function unSetFile ()
{   # Using SetFile from the Apple Developer Tools, reset-to-default all meta data (on an HFS+ file)
    if [ "$1" == "" ]; then 
        echo "Usage: $FUNCNAME file"
    else
        for i in a v b s t c l i n m e d; do SetFile -a $i "$@";done
        SetFile -t '' "$@"
        SetFile -c '' "$@"
    fi
}

