#!/bin/sh -c 'echo This file is meant to be sourced.'

require path || return -1
    # Import my path package...

#bashd_add_to_path_back "/Developer/Tools"
#bashd_add_to_path_back "/Developer/usr/bin"
#bashd_add_to_path_back "/Developer/usr/sbin"
    # Add Xcode tools
    # Duplicate, since I've added all three to /etc/paths.d/Xcode

## GCC...
# Many many settings and flags for gcc based compiles... 
if [ "`uname -s`" == "Darwin" ]
then
    export MACOSX_DEPLOYMENT_TARGET="10.$((`uname -r | awk -F . '{print $1}'`-4))" 
		# Use the full feature set of the linker in the version of Darwin I'm running!
    export SDKROOT="/Developer/SDKs/MacOSX${MACOSX_DEPLOYMENT_TARGET}.sdk"
fi

export OPTFLAGS="-gstabs+ -Os -mtune=native" 
    # generate debugging info, but only store it _inside_ the object; 
    # optimise for speed-and-size;
    # tune for current arch, but 
export ARCHFLAGS="-arch_errors_fatal -arch ppc -arch i386 -arch x86_64" # "Universal" #TODO:FIXME: ppc64?

export CPPFLAGS="${SDKROOT:+--sysroot} ${SDKROOT:-}"
export  LDFLAGS="${SDKROOT:+--sysroot} ${SDKROOT:-}"

export   CFLAGS="-pipe -combine -mfix-and-continue -pie -Wall ${OPTFLAGS}"
export CXXFLAGS="-pipe -combine -mfix-and-continue -pie -Wall ${OPTFLAGS}"
##
export LIBTOOLIZE=glibtoolize
##

# GNU Compiler Collection aliases
 alias gcc='gcc ${CPPFLAGS:-} ${CFLAGS:-}   ${LDFLAGS:-}' 
 alias g++='g++ ${CPPFLAGS:-} ${CXXFLAGS:-} ${LDFLAGS:-}' 
 alias ugcc='gcc ${ARCHFLAGS:-}' # re-use above aliases.
 alias ug++='g++ ${ARCHFLAGS:-}'
