#!/bin/sh -c 'echo "Your father smelt of eldarberries!"'

require prompt_commands || return -1
    # Import my prompt_commands package, required by prompt_command_append()

HISTSIZE=10000
    # Keep a much longer history. (default == 500)
HISTIGNORE="&:l:ls:cd:[bf]g:exit:quit:bye"
    # This kicks-ass! It drops repeats and other useless 
    # things from the command history! 
shopt -s cmdhist histappend histverify no_empty_cmd_completion
    # save multi-line commands as one entry, append to history instead of overwriting,
    #  allow editing of commands retreived from history,
    #  don't list all when completing on blank string,
prompt_command_append "history -a"
    # appent the command history right away
#prompt_command_append "history -n"
    # read in any new entries right away
    # this is resource intensive, requiring disk access after each command...
    # this also has the effect of doubling all of the recent history... so disabled...
