#!/bin/sh

##
# This package enables the use of macports, optionally.
##
# Once the port command is issued, then the macports will be available.
##

require path || return -1

MacPorts="/opt/macports"
if [ ! -d "$MacPorts" ]
then
    MacPorts="/opt/local"
fi

alias port="
    bashd_add_to_path_back $MacPorts/bin
    bashd_add_to_path_back_if_admin $MacPorts/sbin
    alias port='sudo port'
    sudo port"
