#!/bin/sh -c 'echo This file is meant to be sourced.'

import screen
# import my screen package, which is used for isscreen() below.
# this might silently fail, which is OK
# (import might fail; for a noisy failure use require)

# Figure out the incoming hostname for ssh connections
#  I do this because SSH_CONNECTION is preserved by my environment,
#  whereas SSH_HOSTNAME is not (since it is redundant).
unset SSH_HOSTNAME
if [ -n "${SSH_CONNECTION:-}" ]
then 
    for i in `host $(echo $SSH_CONNECTION | awk '{print $1}')`; do SSH_HOSTNAME="$i"; done
    export SSH_HOSTNAME
    unset i
fi

# Reset SSH_CLIENT from SSH_CONNECTION
#  I do this because SSH_CONNECTION is preserved by my environment,
#  whereas SSH_CLIENT is not (since it is redundant).
if [ -n "${SSH_CONNECTION:-}" ]
then
    export SSH_CLIENT=`echo "$SSH_CONNECTION" | awk '{print $1 " " $2 " " $4}'`
fi

function slogin () 
{
    # slogin() is meant to start a new login shell on a remote host,
    #  so it will run the slogin command (ssh) and run screen on the
    #  remote host. If we're running within screen(1), then open a
    #  new window.
    
    if declare -F isscreen >/dev/null && isscreen
    then
        # The last word on the command line is the host name,
        #  since this slogin() function does run a remote command
        #  and the remote command follows the host name immediately.
        for i in "$@"
        do
            # $# == argc
            TITLE="$i"
            # This is a cheap trick to get the last word on the command line
        done
        screen -t "$TITLE" slogin -t "$@" exec screen -xRR
    else
        command slogin -t "$@" exec screen -xRR
    fi
}
