readonly HISTFILE="${XDG_STATE_HOME:-$HOME/.local/state}/ZSH/history"
mkdir -p "${HISTFILE%/*}"

readonly ZSH="${XDG_DATA_HOME:-$HOME/.local/share}/ZSH"
export ZSH

readonly ZSH_CUSTOM="${XDG_CONFIG_HOME:-$HOME/.config}/ZSH"
readonly ZSH_CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/ZSH"
readonly ZSH_COMPDUMP="${XDG_CACHE_HOME:-$HOME/.cache}/ZSH/zcompdump-${HOST/.*/}-${ZSH_VERSION}"

ZSH_THEME=random

plugins=(
	git
	zsh-autosuggestions
	zsh-syntax-highlighting
)
