#!/bin/bash -c 'exit 1'

if false && [ ! "${MacOSX:=0}" -gt 0 ]
then
    eval "$(defaults read ~/.MacOSX/environment | fgrep '=' | sed -e 's/ = /=/g' -e 's/^/export /g')"
    # Here, $MacOSX serves to indicate when my universal/Aqua environment has been loaded.
fi

BASHD=~/.rc.d
    # Where to find my init scripts

declare -a BASHD_LOADED
    # Keep track of loaded init scripts
function import()
{   # How to load my init scripts
    # Usage: `import package1 [package2] [package3] [...]'
    
    for i in "$@"
    do
        if [[ "${BASHD_LOADED[*]:-}" == *bashd_"$i"_bashd* ]]
        then
            continue
            # If we've already loaded this one, then just return.
        fi
        BASHD_LOADED_NEW="${#BASHD_LOADED[@]}"
            # Figure out where to put the next entry

        if [ -f "${BASHD}/$i" ]
        then
            if BASHD_LOADED["$BASHD_LOADED_NEW"]=bashd_"$i"_bashd
            then
                . "${BASHD}/$i" || return 2
            fi
        elif [ -d "${BASHD}/$i" ]
        then
            if BASHD_LOADED["$BASHD_LOADED_NEW"]=bashd_"$i"_bashd
            then
                . "${BASHD}/$i/$i" || return 2
            fi
        else
            echo "$FUNCNAME: Failed to find '$i'." 1>&2
            return 1
        fi
            # Check it, Record it, Source it.
    done
}
alias bashd=import require=import

function rehash()
{
    unset BASHD_LOADED
    declare -a BASHD_LOADED
    
    source ~/.bashrc
}
