#!/bin/bash --interactive -c 'bashrc_dispatch'

###
## bashrc_interactive: all interactive bash shells load this code
###

for rc_mine in  \
                ~/.config/Bash/*.funcs.bash \
                ~/.config/Bash/*.env.bash \
                ~/.config/Bash/*.aliases.bash \
                ~/.config/Bash/*.rc.bash
do
    source "$rc_mine"
done; unset rc_mine

trap _prompt_command_f EXIT

return
    # deliberately return early.
