#!/bin/bash --fail

# Doesn't work…
exit -9

##
# Source ~/.bashrc.d/*.$1.
##

local -r type="basename "$0" | awk -F '.' '{print $2}'"
local -r pkg="$1"

if [ ! "${type}" ]
then
    echo "$(basename "$0"): Can't figure out what I'm supposed to do." 1>&2
    exit -1
fi

##
# .bash_profile: Bring a login _session_ from immediately-post login(1) to usable. This includes setting up inheritable environ(7), starting any appropriate processes, updating logs, &c.
# .bashrc: Set up an _interactive_ shell up. This includes setting up functions, aliases, environ(7) appropriate for interactive commands, &c.
##


pushd ~ 2>/dev/null && { # Init files may assume they're in ~.
if [ "${pkg:-}" ]
    then
        source ~/.bashrc.d/"$pkg"."$type"
        return # Return early.
    fi

    local each
    for each in ~/.bashrc.d/*."$type"
    do
        echo source "$each"
    done
popd 2>/dev/null; } #^$HOME
